# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import handleimage_pb2 as handleimage__pb2


class HandleImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHash = channel.unary_unary(
                '/HandleImage/GetHash',
                request_serializer=handleimage__pb2.Image.SerializeToString,
                response_deserializer=handleimage__pb2.Hash.FromString,
                )
        self.Resize = channel.unary_unary(
                '/HandleImage/Resize',
                request_serializer=handleimage__pb2.ResizeRequest.SerializeToString,
                response_deserializer=handleimage__pb2.Image.FromString,
                )


class HandleImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandleImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHash,
                    request_deserializer=handleimage__pb2.Image.FromString,
                    response_serializer=handleimage__pb2.Hash.SerializeToString,
            ),
            'Resize': grpc.unary_unary_rpc_method_handler(
                    servicer.Resize,
                    request_deserializer=handleimage__pb2.ResizeRequest.FromString,
                    response_serializer=handleimage__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HandleImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandleImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HandleImage/GetHash',
            handleimage__pb2.Image.SerializeToString,
            handleimage__pb2.Hash.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Resize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HandleImage/Resize',
            handleimage__pb2.ResizeRequest.SerializeToString,
            handleimage__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
