apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Application\Kompose\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: client
  name: client
  namespace: chaos-app
spec:
  ports:
    - prtocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: client
status:
  loadBalancer: {}
