version: "2"
services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - 9000:9000
      - 34333:34333
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio124
    command: server --address ":9000" --console-address ":34333" /export
    volumes:
      - ./docker/data:/export
      - ./docker/config:/root/.minio

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672

  handleimage:
    build: ./GrpcHandleImage
    environment:
      PORT: 5001
    ports: 
      - 5001:5001

  client:
    build: ./client
    ports:
      - 3000:3000

  httpserver:
    build: ./http-server
    ports:
      - 8000:8000
    environment: 
      PORT: 8000
      RABBIT_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      QUEUE: test3
  
  ws_server:
    build: ./ws-server
    environment:
      PORT: 4002
      RABBIT_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      QUEUE: test3
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: minio
      MINIO_SECRETKEY: minio124
      MINIO_BUCKET: test
    ports:
      - 4002:4002

  img_consumer:
    restart: always
    build: ./img-consumer
    environment:
      RABBIT_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      RABBIT_QUEUE: test3
      HASHIMAGE_ADDR: handleimage:5001
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: minio
      MINIO_SECRETKEY: minio124
