apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-consumer
  namespace: chaos-app
  labels:
    app: img-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: img-consumer
  template:
    metadata:
      labels:
        app: img-consumer
    spec:
      containers:
        - name: img-consumer
          image: docker.io/teledima/mega-laba-img-consumer:v1
          env:
            - name: RABBIT_URL
              value: "amqp://rabbitmq:rabbitmq@rabbitmq:5672"
            - name: QUEUE
              value: "test3"
            - name: HASHIMAGE_ADDR
              value: "handleimage:5001"
            - name: MINIO_ENDPOINT
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESSKEY
              value: "minio"
            - name: MINIO_SECRETKEY
              value: "minio124"
---
apiVersion: v1
kind: Service
metadata:
  name: img-consumer
  namespace: chaos-app
spec:
  selector:
    app: img-consumer
