apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mega-laba
  namespace: chaos-app
spec:
  rules:
  - http:
      paths:
      - path: /api/websocket
        pathType: Exact
        backend:
          service:
            name: ws-server
            port:
              number: 4002
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: httpserver
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 3000
