apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mega-laba-ws-server
  namespace: chaos-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/websocket
        pathType: Prefix
        backend:
          service:
            name: ws-server
            port:
              number: 4002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mega-laba-httpserver
  namespace: chaos-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /images
        pathType: Prefix
        backend:
          service:
            name: httpserver
            port:
              number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mega-laba-client
  namespace: chaos-app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 3000
