apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ingress-mega-laba-backend
  namespace: chaos-app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ws-server
            port:
              number: 4002
        path: /api/websocket
        pathType: Prefix
      - backend:
          service:
            name: httpserver
            port:
              number: 8000
        path: /images(/|$)(.*)
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mega-laba-client
  namespace: chaos-app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 3000
