# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hashimage_pb2 as hashimage__pb2


class HashImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHash = channel.unary_unary(
                '/HashImage/GetHash',
                request_serializer=hashimage__pb2.ImageRequest.SerializeToString,
                response_deserializer=hashimage__pb2.Reply.FromString,
                )


class HashImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HashImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHash': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHash,
                    request_deserializer=hashimage__pb2.ImageRequest.FromString,
                    response_serializer=hashimage__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HashImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HashImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HashImage/GetHash',
            hashimage__pb2.ImageRequest.SerializeToString,
            hashimage__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
